  name: whatsapp_sticker_maker
  description: This app ix`s for making stickers and adding telegram and whatsapp application

  publish_to: 'none' # Remove this line if you wish to publish to pub.dev

  version: 1.0.0+1

  environment:
    sdk: '>=2.19.2 <3.0.0'  

  dependencies:
    flutter:
      sdk: flutter
    image: ^4.1.3
    path_provider: ^2.0.14
    flutter_image_compress: ^2.1.0
    image_cropper: ^5.0.1
    image_picker: ^0.8.9
    cupertino_icons: ^1.0.2
    top_snackbar_flutter: ^3.0.0+1
    dotted_border: ^2.0.0+3
    get_storage: ^2.1.1
    is_app_installed: ^0.0.4
    flutter_phoenix: ^1.1.1
    adivery: ^4.2.0 


    flutter_native_splash: ^2.2.19
    get: ^4.6.5
    whatsapp_stickers_exporter: ^1.0.0
    # telegram_stickers_import: 
    #   git: https://github.com/RezaHeidary/telegram_stickers_import.git
    flutter_launcher_icons: ^0.13.1
    animated_splash_screen: ^1.3.0
    salomon_bottom_bar: ^3.3.2
    shared_preferences: ^2.2.2
    flutter_share: ^2.0.0
    provider: ^6.1.1
    google_fonts: ^4.0.4
    in_app_review: ^2.0.8
    localstorage: ^4.0.1+4
    photo_view: ^0.14.0
    image_painter: ^0.6.1
    font_awesome_flutter: ^10.6.0
    image_gallery_saver: ^2.0.3
    flutter_photo_editor: ^0.0.3
    oktoast: ^3.4.0


  flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    macos:
      generate: true
      image_path: "path/to/image.png"

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0
    flutter_image_editor: ^2.1.0
    extended_image: ^8.2.0
    image_editor_plus: ^0.2.3

  flutter:
    uses-material-design: true
    assets:
      - assets/

    fonts:
      - family: Sans
        fonts:
          - asset: assets/fonts/sans.ttf
